Repository GameGrumpsJointJustice/courtengine, pull requests merged in 2019-09, with the labels that each got.

#1 Removed unused files
  docs/scripting.html
  episode.meta
Labels: documentation

#2 gavel animation update
  code/trialscriptevents.lua
Labels: enhancement

#3 Smallfont
  sprites/FontImage.png
  sprites/SmallFontImage.png
Labels: enhancement

#12 added basic pause functionality
  README.md
  code/controlscriptevents.lua
  main.lua
Labels: enhancement

#14 Usernameisinuse/initialize compression
  characters/arin/.normal.png-autosave.kra
  characters/arin/Confident_un.png
  characters/arin/DeskSlam_ani.png
  characters/arin/Sweaty_un.png
  characters/butz/Nervous_un.png
  characters/butz/Sweaty_un.png
  characters/butz/ThumbsUp_un.png
  characters/edgeworth/Nope_ani.png
  characters/payne/Sweaty_un.png
  characters/phoenix/DeskSlam_ani.png
  characters/phoenix/Sweaty_un.png
  code/scriptloader.lua
  scripts/arinsoundtest.script
  scripts/e1s1.script
  scripts/e1s2.script
Labels: enhancement

#15 Usernameisinuse/payne objection
  characters/payne/objection.wav
Labels: bug

#18 encapsulated title screen, better text sfx
  code/assets.lua
  code/courtscene.lua
  code/scriptevents.lua
  code/scriptloader.lua
  code/titlescene.lua
  code/trialscriptevents.lua
  main.lua
  scripts/test.script
Labels: enhancement

#19 Usernameisinuse/auto asset import
  backgrounds/BLACK_SCREEN.png
  backgrounds/COURT_ASSISTANT.png
  backgrounds/COURT_DEFENSE_1.png
  backgrounds/COURT_DEFENSE_2.png
  backgrounds/COURT_JUDGE.png
  backgrounds/COURT_PROSECUTION_1.png
  backgrounds/COURT_PROSECUTION_2.png
  backgrounds/COURT_WITNESS_1.png
  backgrounds/COURT_WITNESS_2.png
  backgrounds/LOBBY.png
  backgrounds/prohelperstand.png
  backgrounds/wideshot.png
  code/assets.lua
  code/courtscene.lua
  code/scriptevents.lua
  code/scriptloader.lua
  code/trialscriptevents.lua
  scripts/showoff.script
  sounds/femaletalk.wav
  sounds/gavel.wav
  sounds/maletalk.wav
  sounds/mutter.wav
  sounds/objectionclean.wav
  sounds/selectblip2.wav
  sounds/stab.wav
  sounds/testimony.wav
  sounds/triplegavel.wav
  sounds/typewriter.wav
  sprites/AnonTextBox.png
  sprites/CrossExamination.png
  sprites/FontImage.png~
  sprites/Gavel_1.png
  sprites/Gavel_2.png
  sprites/Gavel_3.png
  sprites/Penalty.png
  sprites/TalkingHead_1.png
  sprites/TalkingHead_2.png
  sprites/TalkingHead_3.png
  sprites/TalkingHead_4.png
  sprites/TextBox.png
  sprites/WideShot.png
  sprites/shouts/holdit.png
  sprites/shouts/objection.png
  sprites/shouts/takethat.png
  sprites/talkingheads1.png~
  sprites/talkingheads2.png~
Labels: enhancement

#20 Bug fix and cleanup for merge 19
  code/assets.lua
  code/trialscriptevents.lua
  sprites/CourtPan.png
Labels: bug

#22 Court record animation also adds the evidence, and includes "added" text
  code/scriptevents.lua
  code/scriptloader.lua
  scripts/e1s2.script
Labels: enhancement

#24 Usernameisinuse/small edits and script
  code/courtscene.lua
  code/scriptevents.lua
  code/scriptloader.lua
  code/utils.lua
  main.lua
  scripts/e1s1.script
  scripts/e1s2.script
  scripts/e1s3.script
  sprites/SmallFontImage.png
Labels: enhancement

#26 added a debug option to the config.lua file and also to a startup args
  code/scriptevents.lua
  config.lua
  main.lua
Labels: enhancement

#25 creation of boldfonts assets and support for them in the engine
  code/assets.lua
  sprites/GameFont.png
  sprites/GameFontBold.png
  sprites/SmallFont.png
  sprites/SmallFontBold.png
Labels: enhancement

#28 play sfx via the script
  code/scriptevents.lua
  code/scriptloader.lua
Labels: enhancement

#29 Usernameisinuse/scripts
  code/scriptevents.lua
  code/scriptloader.lua
  scripts/e1s1.script
Labels: enhancement

#31 Usernameisinuse/icon
  conf.lua
  icon.png
Labels: enhancement
